### ISSUE TITLE
(test): a user can update a post title/body

### ISSUE THREAD

**Issue by 2wce** [2wce/prisma-template#33]

**Comment by Mr-emeka** [comment]
Hello @2wce if you don't mind would love to work on this.

**Comment by 2wce** [comment]
Sure thing @Mr-emeka 👍🏽

**Comment by Mr-emeka** [comment]
Hello @2wce , how do i generate the input type for updating post
Also what input should I have to pass to be able to update a post (post id and author id) ?

**Comment by 2wce** [comment]
sorry about that @Mr-emeka the functionality was still in a local branch 😅 should be available now that #79 has been merged

**Comment by Mr-emeka** [comment]
> the author id usually comes from the auth token, so for a text you just pass an id in the context & you'll be fine. for the actual mutation you can 1st login then if you pass the auth token in the header it will decode the id. hope that helps @Mr-emeka?

Check out my Pr.
